#!/usr/bin/env swift
//
// generate-icon.swift
//
// Generates Replier.app's icon: a flat, two-tone indigo squircle (macOS
// "rounded square" app-icon shape) with the Hugeicons "Re" glyph centered
// on top, standing in for "reply".
//
// Glyph source: @hugeicons/core-free-icons v4.2.3, `ReIcon` (Stroke Rounded
// style, free tier). https://www.npmjs.com/package/@hugeicons/core-free-icons
// License: MIT (see package.json "license" field in the published tarball).
// Only the inner glyph strokes (the "R", the "e", and the two dots that read
// as ":" — i.e. the wordmark "Re:") are used below; the icon's own outer
// rounded-square frame from the source SVG is discarded in favor of our own
// squircle background per the app-icon design brief. Path coordinates below
// are transcribed verbatim (in the source's 24x24 viewBox, SVG y-down space)
// from dist/esm/ReIcon.js in that package.
//
// Usage: swift Scripts/generate-icon.swift
//
// Renders a 1024x1024 master, downsamples it to every size required by a
// macOS .iconset, writes the PNGs into Assets/AppIcon.iconset/, then runs
// `iconutil` to produce Assets/AppIcon.icns.
//
// Re-run this script any time the design constants below change; nothing
// else needs to be regenerated by hand.

import AppKit
import Foundation

// MARK: - Paths

let scriptURL = URL(fileURLWithPath: #filePath)
let repoRoot = scriptURL.deletingLastPathComponent().deletingLastPathComponent()
let assetsDir = repoRoot.appendingPathComponent("Assets")
let iconsetDir = assetsDir.appendingPathComponent("AppIcon.iconset")
let icnsURL = assetsDir.appendingPathComponent("AppIcon.icns")

// MARK: - Design constants

let masterSize: CGFloat = 1024

/// Standard macOS "squircle" proportions (rounded-rect approximation).
let cornerRadiusRatio: CGFloat = 0.2237

/// Fraction of the canvas width the glyph's bounding box should occupy.
let glyphBoxRatio: CGFloat = 0.57

let backgroundTop = NSColor(srgbRed: 0x66 / 255, green: 0x72 / 255, blue: 0xE0 / 255, alpha: 1)
let backgroundBottom = NSColor(srgbRed: 0x4C / 255, green: 0x56 / 255, blue: 0xC9 / 255, alpha: 1) // indigo, ~#5A67D8 family
let glyphColor = NSColor(srgbRed: 0xFB / 255, green: 0xFC / 255, blue: 0xFF / 255, alpha: 1) // near-white

// MARK: - Glyph geometry (source: Hugeicons `ReIcon`, 24x24 viewBox, MIT)

/// The "R" — a stem with a single curved branch, in the source's minimalist
/// stroke style (no closed bowl).
func glyphPathR() -> CGPath {
    let path = CGMutablePath()
    path.move(to: CGPoint(x: 6.5, y: 14))
    path.addCurve(to: CGPoint(x: 9.5, y: 13.5),
                   control1: CGPoint(x: 6.5, y: 14), control2: CGPoint(x: 8, y: 12))
    path.move(to: CGPoint(x: 6.5, y: 14))
    path.addLine(to: CGPoint(x: 6.5, y: 17.5))
    path.move(to: CGPoint(x: 6.5, y: 14))
    path.addLine(to: CGPoint(x: 6.5, y: 12.5))
    return path
}

/// The "e" — single-story lowercase e (closed top bowl, open aperture at
/// bottom-right).
func glyphPathE() -> CGPath {
    let path = CGMutablePath()
    path.move(to: CGPoint(x: 11.5, y: 15))
    path.addLine(to: CGPoint(x: 11.5, y: 14.25))
    path.addCurve(to: CGPoint(x: 13.25, y: 12.5),
                   control1: CGPoint(x: 11.5, y: 13.2835), control2: CGPoint(x: 12.2835, y: 12.5))
    path.addCurve(to: CGPoint(x: 15, y: 14.25),
                   control1: CGPoint(x: 14.2165, y: 12.5), control2: CGPoint(x: 15, y: 13.2835))
    path.addLine(to: CGPoint(x: 15, y: 15))
    path.addLine(to: CGPoint(x: 11.5, y: 15))
    path.move(to: CGPoint(x: 11.5, y: 15))
    path.addLine(to: CGPoint(x: 11.5, y: 15.75))
    path.addCurve(to: CGPoint(x: 13.25, y: 17.5),
                   control1: CGPoint(x: 11.5, y: 16.7165), control2: CGPoint(x: 12.2835, y: 17.5))
    path.addCurve(to: CGPoint(x: 14.5, y: 16.9747),
                   control1: CGPoint(x: 13.7397, y: 17.5), control2: CGPoint(x: 14.1824, y: 17.2989))
    return path
}

/// The two dots that read as ":" after "Re", completing the "Re:" wordmark.
func glyphDots() -> [CGPath] {
    let radius: CGFloat = 0.28
    return [
        CGPath(ellipseIn: CGRect(x: 18 - radius, y: 13 - radius, width: radius * 2, height: radius * 2), transform: nil),
        CGPath(ellipseIn: CGRect(x: 18 - radius, y: 17 - radius, width: radius * 2, height: radius * 2), transform: nil),
    ]
}

let strokedGlyphPaths: [CGPath] = [glyphPathR(), glyphPathE()]
let filledGlyphPaths: [CGPath] = glyphDots()
let sourceStrokeWidth: CGFloat = 1.5 // matches strokeWidth in the source SVG (24-unit viewBox)

// MARK: - Drawing helpers

func squirclePath(in rect: CGRect, cornerRatio: CGFloat) -> CGPath {
    let radius = min(rect.width, rect.height) * cornerRatio
    return CGPath(roundedRect: rect, cornerWidth: radius, cornerHeight: radius, transform: nil)
}

func combinedGlyphBounds() -> CGRect {
    var bounds: CGRect?
    for path in strokedGlyphPaths + filledGlyphPaths {
        let box = path.boundingBoxOfPath
        bounds = bounds.map { $0.union(box) } ?? box
    }
    return bounds ?? .zero
}

func drawMasterIcon() -> NSImage {
    let size = masterSize
    let image = NSImage(size: CGSize(width: size, height: size))
    image.lockFocusFlipped(true) // y-down, top-left origin — matches SVG source space.
    defer { image.unlockFocus() }

    guard let ctx = NSGraphicsContext.current?.cgContext else {
        fatalError("no graphics context")
    }

    let bounds = CGRect(x: 0, y: 0, width: size, height: size)

    // 1. Clip to the squircle canvas and paint the background gradient.
    ctx.saveGState()
    ctx.addPath(squirclePath(in: bounds, cornerRatio: cornerRadiusRatio))
    ctx.clip()

    let bgGradient = CGGradient(colorsSpace: CGColorSpaceCreateDeviceRGB(),
                                 colors: [backgroundTop.cgColor, backgroundBottom.cgColor] as CFArray,
                                 locations: [0, 1])!
    ctx.drawLinearGradient(bgGradient,
                            start: CGPoint(x: size / 2, y: 0),
                            end: CGPoint(x: size / 2, y: size),
                            options: [])
    ctx.restoreGState()

    // 2. Place the "Re:" glyph centered at ~57% of the canvas width, scaled
    //    uniformly (preserving the source's proportions) and stroked in the
    //    contrasting foreground color.
    let glyphBounds = combinedGlyphBounds()
    let targetBoxSize = size * glyphBoxRatio
    let scale = min(targetBoxSize / glyphBounds.width, targetBoxSize / glyphBounds.height)
    let scaledWidth = glyphBounds.width * scale
    let scaledHeight = glyphBounds.height * scale
    let originX = (size - scaledWidth) / 2 - glyphBounds.minX * scale
    let originY = (size - scaledHeight) / 2 - glyphBounds.minY * scale

    var transform = CGAffineTransform(translationX: originX, y: originY).scaledBy(x: scale, y: scale)

    ctx.saveGState()
    ctx.setStrokeColor(glyphColor.cgColor)
    ctx.setFillColor(glyphColor.cgColor)
    ctx.setLineWidth(sourceStrokeWidth * scale)
    ctx.setLineCap(.round)
    ctx.setLineJoin(.round)

    for path in strokedGlyphPaths {
        guard let transformed = path.copy(using: &transform) else { continue }
        ctx.addPath(transformed)
        ctx.strokePath()
    }
    for path in filledGlyphPaths {
        guard let transformed = path.copy(using: &transform) else { continue }
        ctx.addPath(transformed)
        ctx.fillPath()
    }
    ctx.restoreGState()

    return image
}

func resized(_ image: NSImage, to size: Int) -> NSBitmapImageRep {
    guard let sourceCG = image.cgImage(forProposedRect: nil, context: nil, hints: nil) else {
        fatalError("failed to get master CGImage")
    }
    let colorSpace = CGColorSpaceCreateDeviceRGB()
    guard let ctx = CGContext(data: nil,
                               width: size, height: size,
                               bitsPerComponent: 8,
                               bytesPerRow: 0,
                               space: colorSpace,
                               bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue) else {
        fatalError("failed to create bitmap context")
    }
    ctx.interpolationQuality = .high
    ctx.draw(sourceCG, in: CGRect(origin: .zero, size: CGSize(width: size, height: size)))
    guard let outCG = ctx.makeImage() else { fatalError("failed to render resized image") }
    return NSBitmapImageRep(cgImage: outCG)
}

extension NSBitmapImageRep {
    func pngWrite(to url: URL) throws {
        guard let data = representation(using: .png, properties: [:]) else {
            throw NSError(domain: "generate-icon", code: 1, userInfo: [NSLocalizedDescriptionKey: "PNG encoding failed"])
        }
        try data.write(to: url)
    }
}

// MARK: - Render + export

let iconSizes: [(name: String, size: Int)] = [
    ("icon_16x16", 16),
    ("icon_16x16@2x", 32),
    ("icon_32x32", 32),
    ("icon_32x32@2x", 64),
    ("icon_128x128", 128),
    ("icon_128x128@2x", 256),
    ("icon_256x256", 256),
    ("icon_256x256@2x", 512),
    ("icon_512x512", 512),
    ("icon_512x512@2x", 1024),
]

let fm = FileManager.default
try? fm.removeItem(at: iconsetDir)
try fm.createDirectory(at: iconsetDir, withIntermediateDirectories: true)

let master = drawMasterIcon()

// Full-resolution preview for quick visual review (not part of the iconset).
let previewURL = URL(fileURLWithPath: NSTemporaryDirectory()).appendingPathComponent("AppIcon-preview.png")
try resized(master, to: Int(masterSize)).pngWrite(to: previewURL)
print("wrote preview: \(previewURL.path)")

for entry in iconSizes {
    let rep = resized(master, to: entry.size)
    let url = iconsetDir.appendingPathComponent("\(entry.name).png")
    try rep.pngWrite(to: url)
    print("wrote \(url.path) (\(entry.size)x\(entry.size))")
}

print("==> iconutil -c icns")
let process = Process()
process.executableURL = URL(fileURLWithPath: "/usr/bin/iconutil")
process.arguments = ["-c", "icns", iconsetDir.path, "-o", icnsURL.path]
try process.run()
process.waitUntilExit()
guard process.terminationStatus == 0 else {
    fatalError("iconutil failed with status \(process.terminationStatus)")
}
print("wrote \(icnsURL.path)")
